In [63]:
from dotenv import load_dotenv
load_dotenv()

True

In [64]:
import os

import pandas as pd
import mlflow
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import (
    OneHotEncoder, 
    SplineTransformer, 
    QuantileTransformer, 
    RobustScaler,
    PolynomialFeatures,
    KBinsDiscretizer,
)

TABLE_NAME = "clean_users_churn"

TRACKING_SERVER_HOST = "127.0.0.1"
TRACKING_SERVER_PORT = 5000

EXPERIMENT_NAME = "churn_simonreise"
RUN_NAME = "preprocessing" 
REGISTRY_MODEL_NAME = "churn_model_simonreise_catboost_basic"

In [79]:
import psycopg

connection = {"sslmode": "require", "target_session_attrs": "read-write"}
postgres_credentials = {
    "host": os.getenv("DB_DESTINATION_HOST"),
    "port": os.getenv("DB_DESTINATION_PORT"),
    "dbname": os.getenv("DB_DESTINATION_NAME"),
    "user": os.getenv("DB_DESTINATION_USER"),
    "password": os.getenv("DB_DESTINATION_PASSWORD"),
}

connection.update(postgres_credentials)

with psycopg.connect(**connection) as conn:

    with conn.cursor() as cur:
        cur.execute(f"SELECT * FROM {TABLE_NAME}")
        data = cur.fetchall()
        columns = [col[0] for col in cur.description]

df = pd.DataFrame(data, columns=columns)

df.head(2)

,id,customer_id,begin_date,end_date,type,paperless_billing,payment_method,monthly_charges,total_charges,internet_service,...,device_protection,tech_support,streaming_tv,streaming_movies,gender,senior_citizen,partner,dependents,multiple_lines,target
0,1,9763-GRSKD,2019-01-01,NaT,Month-to-month,Yes,Mailed check,49.95,587.45,DSL,...,No,No,No,No,Male,0,Yes,Yes,No,0
1,2,8402-OOOHJ,2016-09-01,NaT,Two year,No,Mailed check,20.65,835.15,Fiber optic,...,No,No,No,No,Female,0,No,No,No,0

In [80]:
obj_df = df.select_dtypes(include="object")

In [82]:
# определение категориальных колонок, которые будут преобразованы
cat_columns = ["type", "payment_method", "internet_service", "gender"]

# создание объекта OneHotEncoder для преобразования категориальных переменных
# auto - автоматическое определение категорий
# ignore - игнорировать ошибки, если встречается неизвестная категория
# max_categories - максимальное количество уникальных категорий
# sparse_output - вывод в виде разреженной матрицы, если False, то в виде обычного массива
# drop="first" - удаляет первую категорию, чтобы избежать ловушки мультиколлинеарности
encoder_oh = OneHotEncoder(categories="auto", max_categories=10, handle_unknown="ignore", drop="first", sparse_output=False)

# применение OneHotEncoder к данным. Преобразование категориальных данных в массив
encoded_features = encoder_oh.fit_transform(obj_df)
# преобразование полученных признаков в DataFrame и установка названий колонок
# get_feature_names_out() - получение имён признаков после преобразования
encoded_df = pd.DataFrame(encoded_features, columns=encoder_oh.get_feature_names_out())

# конкатенация исходного DataFrame с новым DataFrame, содержащим закодированные категориальные признаки
# axis=1 означает конкатенацию по колонкам
obj_df = pd.concat([obj_df, encoded_df], axis=1)

obj_df.head(2)

,customer_id,type,paperless_billing,payment_method,internet_service,online_security,online_backup,device_protection,tech_support,streaming_tv,...,online_security_Yes_1.0,online_backup_Yes_1.0,device_protection_Yes_1.0,tech_support_Yes_1.0,streaming_tv_Yes_1.0,streaming_movies_Yes_1.0,gender_Male_1.0,partner_Yes_1.0,dependents_Yes_1.0,multiple_lines_Yes_1.0
0,9763-GRSKD,Month-to-month,Yes,Mailed check,DSL,Yes,No,No,No,No,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0
1,8402-OOOHJ,Two year,No,Mailed check,Fiber optic,No,No,No,No,No,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [83]:
num_columns = ["monthly_charges", "total_charges"]
num_df = df[num_columns]

n_knots = 3
degree_spline = 4
n_quantiles=100
degree = 3
n_bins = 5
encode = 'ordinal'
strategy = 'uniform'
subsample = None


# SplineTransformer
encoder_spl = SplineTransformer(n_knots=n_knots, degree=degree_spline)
encoded_features = encoder_spl.fit_transform(df[num_columns])

encoded_df = pd.DataFrame(encoded_features, columns=encoder_spl.get_feature_names_out())
num_df = pd.concat([num_df, encoded_df], axis=1)


# QuantileTransformer
encoder_q = QuantileTransformer(n_quantiles=n_quantiles)
encoded_features = encoder_q.fit_transform(df[num_columns])

encoded_df = pd.DataFrame(encoded_features, columns=encoder_q.get_feature_names_out())
encoded_df.columns = [col + f"_q_{n_quantiles}" for col in num_columns]
num_df = pd.concat([num_df, encoded_df], axis=1)


# RobustScaler
encoder_rb = RobustScaler()
encoded_features = encoder_rb.fit_transform(df[num_columns])

encoded_df = pd.DataFrame(encoded_features, columns=encoder_rb.get_feature_names_out())
encoded_df.columns = [col + f"_robust" for col in num_columns]
num_df = pd.concat([num_df, encoded_df], axis=1)


# PolynomialFeatures
encoder_pol = PolynomialFeatures(degree=degree)
encoded_features = encoder_pol.fit_transform(df[num_columns])

encoded_df = pd.DataFrame(encoded_features, columns=encoder_pol.get_feature_names_out())
# get all columns after the intercept and original features
encoded_df = encoded_df.iloc[:, 1 + len(num_columns):]
encoded_df.columns = encoder_pol.get_feature_names_out()[1 + len(num_columns):]
num_df = pd.concat([num_df, encoded_df], axis=1)

# KBinsDiscretizer
encoder_kbd = KBinsDiscretizer(n_bins=n_bins, encode=encode, strategy=strategy, subsample=subsample)
encoded_features = encoder_kbd.fit_transform(df[num_columns])

encoded_df = pd.DataFrame(encoded_features, columns=encoder_kbd.get_feature_names_out())
encoded_df.columns = [col + f"_bin" for col in num_columns]
num_df = pd.concat([num_df, encoded_df], axis=1)


num_df.head(2)

,monthly_charges,total_charges,monthly_charges_sp_0,monthly_charges_sp_1,monthly_charges_sp_2,monthly_charges_sp_3,monthly_charges_sp_4,monthly_charges_sp_5,total_charges_sp_0,total_charges_sp_1,...,total_charges_robust,monthly_charges^2,monthly_charges total_charges,total_charges^2,monthly_charges^3,monthly_charges^2 total_charges,monthly_charges total_charges^2,total_charges^3,monthly_charges_bin,total_charges_bin
0,49.95,587.45,0.000774,0.142550,0.588331,0.261746,6.599052e-03,0.0,0.023735,0.389490,...,-0.242592,2495.0025,29343.1275,345097.5025,124625.374875,1.465689e+06,1.723762e+07,2.027275e+08,1.0,0.0
1,20.65,835.15,0.034259,0.433936,0.481590,0.050214,2.168151e-07,0.0,0.018078,0.358392,...,-0.169561,426.4225,17245.8475,697475.5225,8805.624625,3.561268e+05,1.440287e+07,5.824967e+08,0.0,0.0

In [84]:
numeric_transformer = ColumnTransformer(transformers=[
		("spl", encoder_spl, num_columns),
        ("q", encoder_q, num_columns),
        ("rb", encoder_rb, num_columns),
        ("pol", encoder_pol, num_columns),
        ("kbd", encoder_kbd, num_columns),
	]
)

categorical_transformer = Pipeline(steps=[
	    ("encoder", encoder_oh),
    ]
)

preprocessor = ColumnTransformer(transformers=[
	    ("num", numeric_transformer, num_columns),
        ("cat", categorical_transformer, cat_columns),
    ], n_jobs=-1,
)

encoded_features = preprocessor.fit_transform(df)

transformed_df = pd.DataFrame(encoded_features, columns=preprocessor.get_feature_names_out())

df = pd.concat([df, transformed_df], axis=1)
df.head(2)

,id,customer_id,begin_date,end_date,type,paperless_billing,payment_method,monthly_charges,total_charges,internet_service,...,num__pol__total_charges^3,num__kbd__monthly_charges,num__kbd__total_charges,cat__type_One year,cat__type_Two year,cat__payment_method_Credit card (automatic),cat__payment_method_Electronic check,cat__payment_method_Mailed check,cat__internet_service_Fiber optic,cat__gender_Male
0,1,9763-GRSKD,2019-01-01,NaT,Month-to-month,Yes,Mailed check,49.95,587.45,DSL,...,2.027275e+08,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
1,2,8402-OOOHJ,2016-09-01,NaT,Two year,No,Mailed check,20.65,835.15,Fiber optic,...,5.824967e+08,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0

In [85]:
preprocessor

ColumnTransformer(n_jobs=-1,
                  transformers=[('num',
                                 ColumnTransformer(transformers=[('spl',
                                                                  SplineTransformer(degree=4,
                                                                                    n_knots=3),
                                                                  ['monthly_charges',
                                                                   'total_charges']),
                                                                 ('q',
                                                                  QuantileTransformer(n_quantiles=100),
                                                                  ['monthly_charges',
                                                                   'total_charges']),
                                                                 ('rb',
                                                                  RobustScaler(),
                                                                  ['monthly_charges',
                                                                   'total_charges']),
                                                                 ('pol',
                                                                  PolynomialFeatures(degree=3),
                                                                  ['monthly_char...
                                                                   'total_charges']),
                                                                 ('kbd',
                                                                  KBinsDiscretizer(encode='ordinal',
                                                                                   strategy='uniform',
                                                                                   subsample=None),
                                                                  ['monthly_charges',
                                                                   'total_charges'])]),
                                 ['monthly_charges', 'total_charges']),
                                ('cat',
                                 Pipeline(steps=[('encoder',
                                                  OneHotEncoder(drop='first',
                                                                handle_unknown='ignore',
                                                                max_categories=10,
                                                                sparse_output=False))]),
                                 ['type', 'payment_method', 'internet_service',
                                  'gender'])])

In [54]:
os.environ["MLFLOW_S3_ENDPOINT_URL"] = "https://storage.yandexcloud.net"
os.environ["AWS_ACCESS_KEY_ID"] = os.getenv("AWS_ACCESS_KEY_ID")
os.environ["AWS_SECRET_ACCESS_KEY"] = os.getenv("AWS_SECRET_ACCESS_KEY")

mlflow.set_tracking_uri(f"http://{TRACKING_SERVER_HOST}:{TRACKING_SERVER_PORT}")
mlflow.set_registry_uri(f"http://{TRACKING_SERVER_HOST}:{TRACKING_SERVER_PORT}")

experiment_id = mlflow.get_experiment_by_name(EXPERIMENT_NAME).experiment_id

with mlflow.start_run(run_name=RUN_NAME, experiment_id=experiment_id) as run:
    run_id = run.info.run_id

    mlflow.sklearn.log_model(preprocessor, "column_transformer")

2026/03/07 08:21:31 WARNING mlflow.sklearn: Model was missing function: predict. Not logging python_function flavor!

In [55]:
run_id

'4152ee89475a47a2b86ec2275fb0c5e7'

In [86]:
from catboost import CatBoostClassifier

In [87]:
df = df.drop(columns=["id", "end_date", "customer_id"])

In [88]:
model = CatBoostClassifier(auto_class_weights='Balanced')

In [97]:
model.fit(df.drop(columns=["target"]), df["target"], cat_features=df.select_dtypes(include=["object"]).columns.tolist())

Learning rate set to 0.023675
0:	learn: 0.6825597	total: 73.4ms	remaining: 1m 13s
1:	learn: 0.6703049	total: 87.7ms	remaining: 43.8s
2:	learn: 0.6608331	total: 102ms	remaining: 33.8s
3:	learn: 0.6512929	total: 115ms	remaining: 28.7s
4:	learn: 0.6430910	total: 129ms	remaining: 25.8s
5:	learn: 0.6325470	total: 144ms	remaining: 23.8s
6:	learn: 0.6245581	total: 159ms	remaining: 22.6s
7:	learn: 0.6151093	total: 173ms	remaining: 21.4s
8:	learn: 0.6084784	total: 188ms	remaining: 20.7s
9:	learn: 0.6024058	total: 202ms	remaining: 20s
10:	learn: 0.5946163	total: 216ms	remaining: 19.5s
11:	learn: 0.5886462	total: 230ms	remaining: 19s
12:	learn: 0.5809660	total: 245ms	remaining: 18.6s
13:	learn: 0.5762870	total: 260ms	remaining: 18.3s
14:	learn: 0.5711174	total: 277ms	remaining: 18.2s
15:	learn: 0.5647712	total: 291ms	remaining: 17.9s
16:	learn: 0.5601078	total: 304ms	remaining: 17.6s
17:	learn: 0.5565149	total: 318ms	remaining: 17.4s
18:	learn: 0.5525235	total: 332ms	remaining: 17.1s
19:	learn: 0.5488639	total: 345ms	remaining: 16.9s
20:	learn: 0.5448144	total: 358ms	remaining: 16.7s
21:	learn: 0.5401034	total: 372ms	remaining: 16.5s
22:	learn: 0.5369335	total: 386ms	remaining: 16.4s
23:	learn: 0.5341382	total: 399ms	remaining: 16.2s
24:	learn: 0.5294861	total: 414ms	remaining: 16.2s
25:	learn: 0.5261995	total: 431ms	remaining: 16.1s
26:	learn: 0.5238769	total: 448ms	remaining: 16.1s
27:	learn: 0.5209795	total: 462ms	remaining: 16s
28:	learn: 0.5185469	total: 476ms	remaining: 15.9s
29:	learn: 0.5157430	total: 490ms	remaining: 15.8s
30:	learn: 0.5132856	total: 504ms	remaining: 15.8s
31:	learn: 0.5113919	total: 518ms	remaining: 15.7s
32:	learn: 0.5092898	total: 532ms	remaining: 15.6s
33:	learn: 0.5073466	total: 547ms	remaining: 15.5s
34:	learn: 0.5046875	total: 561ms	remaining: 15.5s
35:	learn: 0.5019768	total: 575ms	remaining: 15.4s
36:	learn: 0.4996579	total: 588ms	remaining: 15.3s
37:	learn: 0.4980102	total: 602ms	remaining: 15.2s
38:	learn: 0.4962870	total: 617ms	remaining: 15.2s
39:	learn: 0.4931756	total: 631ms	remaining: 15.1s
40:	learn: 0.4916067	total: 644ms	remaining: 15.1s
41:	learn: 0.4899573	total: 658ms	remaining: 15s
42:	learn: 0.4886595	total: 673ms	remaining: 15s
43:	learn: 0.4860901	total: 688ms	remaining: 14.9s
44:	learn: 0.4839182	total: 701ms	remaining: 14.9s
45:	learn: 0.4819578	total: 716ms	remaining: 14.9s
46:	learn: 0.4804615	total: 732ms	remaining: 14.8s
47:	learn: 0.4783029	total: 746ms	remaining: 14.8s
48:	learn: 0.4773326	total: 759ms	remaining: 14.7s
49:	learn: 0.4759055	total: 774ms	remaining: 14.7s
50:	learn: 0.4750947	total: 788ms	remaining: 14.7s
51:	learn: 0.4739421	total: 801ms	remaining: 14.6s
52:	learn: 0.4719878	total: 814ms	remaining: 14.5s
53:	learn: 0.4708621	total: 830ms	remaining: 14.5s
54:	learn: 0.4698404	total: 844ms	remaining: 14.5s
55:	learn: 0.4683311	total: 857ms	remaining: 14.5s
56:	learn: 0.4673354	total: 871ms	remaining: 14.4s
57:	learn: 0.4655635	total: 885ms	remaining: 14.4s
58:	learn: 0.4645858	total: 898ms	remaining: 14.3s
59:	learn: 0.4632185	total: 911ms	remaining: 14.3s
60:	learn: 0.4612273	total: 925ms	remaining: 14.2s
61:	learn: 0.4609318	total: 931ms	remaining: 14.1s
62:	learn: 0.4601202	total: 947ms	remaining: 14.1s
63:	learn: 0.4593502	total: 960ms	remaining: 14s
64:	learn: 0.4587651	total: 975ms	remaining: 14s
65:	learn: 0.4576500	total: 988ms	remaining: 14s
66:	learn: 0.4569246	total: 1s	remaining: 13.9s
67:	learn: 0.4560346	total: 1.01s	remaining: 13.9s
68:	learn: 0.4552962	total: 1.03s	remaining: 13.9s
69:	learn: 0.4541962	total: 1.08s	remaining: 14.3s
70:	learn: 0.4534177	total: 1.11s	remaining: 14.5s
71:	learn: 0.4522819	total: 1.16s	remaining: 14.9s
72:	learn: 0.4516090	total: 1.2s	remaining: 15.2s
73:	learn: 0.4510223	total: 1.24s	remaining: 15.5s
74:	learn: 0.4504238	total: 1.3s	remaining: 16.1s
75:	learn: 0.4490922	total: 1.35s	remaining: 16.4s
76:	learn: 0.4481306	total: 1.41s	remaining: 16.9s
77:	learn: 0.4476863	total: 1.47s	remaining: 17.3s
78:	learn: 0.4471831	total: 1.52s	remaining: 17.7s
79:	learn: 0.4467632	total: 1.58s	remaining: 18.2s
80:	learn: 0.4460659	total: 1.65s	remaining: 18.7s
81:	learn: 0.4456185	total: 1.71s	remaining: 19.1s
82:	learn: 0.4447378	total: 1.75s	remaining: 19.3s
83:	learn: 0.4441728	total: 1.8s	remaining: 19.7s
84:	learn: 0.4434847	total: 1.85s	remaining: 19.9s
85:	learn: 0.4430439	total: 1.86s	remaining: 19.8s
86:	learn: 0.4422169	total: 1.89s	remaining: 19.8s
87:	learn: 0.4414983	total: 1.95s	remaining: 20.2s
88:	learn: 0.4403317	total: 1.98s	remaining: 20.3s
89:	learn: 0.4392938	total: 2.03s	remaining: 20.5s
90:	learn: 0.4388509	total: 2.08s	remaining: 20.8s
91:	learn: 0.4377185	total: 2.1s	remaining: 20.7s
92:	learn: 0.4372234	total: 2.12s	remaining: 20.6s
93:	learn: 0.4366633	total: 2.13s	remaining: 20.5s
94:	learn: 0.4358674	total: 2.15s	remaining: 20.4s
95:	learn: 0.4349246	total: 2.16s	remaining: 20.4s
96:	learn: 0.4338151	total: 2.18s	remaining: 20.3s
97:	learn: 0.4329978	total: 2.19s	remaining: 20.2s
98:	learn: 0.4320556	total: 2.21s	remaining: 20.1s
99:	learn: 0.4314919	total: 2.22s	remaining: 20s
100:	learn: 0.4308461	total: 2.24s	remaining: 19.9s
101:	learn: 0.4305435	total: 2.25s	remaining: 19.8s
102:	learn: 0.4300666	total: 2.27s	remaining: 19.7s
103:	learn: 0.4297170	total: 2.28s	remaining: 19.6s
104:	learn: 0.4290886	total: 2.29s	remaining: 19.5s
105:	learn: 0.4289857	total: 2.3s	remaining: 19.4s
106:	learn: 0.4287652	total: 2.31s	remaining: 19.3s
107:	learn: 0.4282995	total: 2.32s	remaining: 19.2s
108:	learn: 0.4280487	total: 2.34s	remaining: 19.1s
109:	learn: 0.4275736	total: 2.35s	remaining: 19s
110:	learn: 0.4270416	total: 2.37s	remaining: 19s
111:	learn: 0.4267439	total: 2.38s	remaining: 18.9s
112:	learn: 0.4258309	total: 2.4s	remaining: 18.8s
113:	learn: 0.4255191	total: 2.41s	remaining: 18.7s
114:	learn: 0.4247554	total: 2.42s	remaining: 18.7s
115:	learn: 0.4244122	total: 2.44s	remaining: 18.6s
116:	learn: 0.4238252	total: 2.45s	remaining: 18.5s
117:	learn: 0.4232256	total: 2.47s	remaining: 18.5s
118:	learn: 0.4226091	total: 2.48s	remaining: 18.4s
119:	learn: 0.4220117	total: 2.5s	remaining: 18.3s
120:	learn: 0.4211795	total: 2.51s	remaining: 18.3s
121:	learn: 0.4210188	total: 2.52s	remaining: 18.2s
122:	learn: 0.4203123	total: 2.54s	remaining: 18.1s
123:	learn: 0.4199567	total: 2.56s	remaining: 18.1s
124:	learn: 0.4189920	total: 2.59s	remaining: 18.1s
125:	learn: 0.4187160	total: 2.64s	remaining: 18.3s
126:	learn: 0.4185775	total: 2.68s	remaining: 18.5s
127:	learn: 0.4181706	total: 2.75s	remaining: 18.7s
128:	learn: 0.4178017	total: 2.79s	remaining: 18.9s
129:	learn: 0.4169376	total: 2.85s	remaining: 19.1s
130:	learn: 0.4168902	total: 2.86s	remaining: 19s
131:	learn: 0.4166242	total: 2.9s	remaining: 19.1s
132:	learn: 0.4156794	total: 2.96s	remaining: 19.3s
133:	learn: 0.4153718	total: 3.02s	remaining: 19.5s
134:	learn: 0.4151340	total: 3.06s	remaining: 19.6s
135:	learn: 0.4149859	total: 3.08s	remaining: 19.6s
136:	learn: 0.4146916	total: 3.13s	remaining: 19.8s
137:	learn: 0.4144941	total: 3.18s	remaining: 19.8s
138:	learn: 0.4143648	total: 3.23s	remaining: 20s
139:	learn: 0.4139343	total: 3.29s	remaining: 20.2s
140:	learn: 0.4132994	total: 3.32s	remaining: 20.2s
141:	learn: 0.4130937	total: 3.36s	remaining: 20.3s
142:	learn: 0.4128716	total: 3.41s	remaining: 20.4s
143:	learn: 0.4123209	total: 3.47s	remaining: 20.6s
144:	learn: 0.4119994	total: 3.52s	remaining: 20.8s
145:	learn: 0.4117666	total: 3.58s	remaining: 20.9s
146:	learn: 0.4113020	total: 3.62s	remaining: 21s
147:	learn: 0.4111599	total: 3.63s	remaining: 20.9s
148:	learn: 0.4106769	total: 3.64s	remaining: 20.8s
149:	learn: 0.4105160	total: 3.65s	remaining: 20.7s
150:	learn: 0.4097296	total: 3.67s	remaining: 20.6s
151:	learn: 0.4093296	total: 3.68s	remaining: 20.6s
152:	learn: 0.4090684	total: 3.7s	remaining: 20.5s
153:	learn: 0.4086905	total: 3.71s	remaining: 20.4s
154:	learn: 0.4083529	total: 3.73s	remaining: 20.3s
155:	learn: 0.4082932	total: 3.74s	remaining: 20.2s
156:	learn: 0.4077564	total: 3.75s	remaining: 20.1s
157:	learn: 0.4075393	total: 3.77s	remaining: 20.1s
158:	learn: 0.4069109	total: 3.78s	remaining: 20s
159:	learn: 0.4064006	total: 3.79s	remaining: 19.9s
160:	learn: 0.4063045	total: 3.81s	remaining: 19.8s
161:	learn: 0.4060484	total: 3.82s	remaining: 19.8s
162:	learn: 0.4058479	total: 3.83s	remaining: 19.7s
163:	learn: 0.4052644	total: 3.85s	remaining: 19.6s
164:	learn: 0.4051768	total: 3.86s	remaining: 19.5s
165:	learn: 0.4047708	total: 3.88s	remaining: 19.5s
166:	learn: 0.4045249	total: 3.89s	remaining: 19.4s
167:	learn: 0.4043636	total: 3.9s	remaining: 19.3s
168:	learn: 0.4039012	total: 3.92s	remaining: 19.3s
169:	learn: 0.4036219	total: 3.94s	remaining: 19.2s
170:	learn: 0.4034174	total: 3.95s	remaining: 19.2s
171:	learn: 0.4028905	total: 3.97s	remaining: 19.1s
172:	learn: 0.4026276	total: 4s	remaining: 19.1s
173:	learn: 0.4024769	total: 4.01s	remaining: 19.1s
174:	learn: 0.4021218	total: 4.03s	remaining: 19s
175:	learn: 0.4015761	total: 4.04s	remaining: 18.9s
176:	learn: 0.4013151	total: 4.05s	remaining: 18.8s
177:	learn: 0.4011297	total: 4.07s	remaining: 18.8s
178:	learn: 0.4006073	total: 4.08s	remaining: 18.7s
179:	learn: 0.4001871	total: 4.1s	remaining: 18.7s
180:	learn: 0.3999470	total: 4.11s	remaining: 18.6s
181:	learn: 0.3997674	total: 4.13s	remaining: 18.5s
182:	learn: 0.3994630	total: 4.14s	remaining: 18.5s
183:	learn: 0.3984935	total: 4.16s	remaining: 18.5s
184:	learn: 0.3983152	total: 4.18s	remaining: 18.4s
185:	learn: 0.3981958	total: 4.21s	remaining: 18.4s
186:	learn: 0.3980300	total: 4.22s	remaining: 18.4s
187:	learn: 0.3979411	total: 4.24s	remaining: 18.3s
188:	learn: 0.3976821	total: 4.25s	remaining: 18.2s
189:	learn: 0.3973625	total: 4.26s	remaining: 18.2s
190:	learn: 0.3973596	total: 4.27s	remaining: 18.1s
191:	learn: 0.3970472	total: 4.29s	remaining: 18s
192:	learn: 0.3966774	total: 4.3s	remaining: 18s
193:	learn: 0.3966394	total: 4.3s	remaining: 17.9s
194:	learn: 0.3963170	total: 4.32s	remaining: 17.8s
195:	learn: 0.3959077	total: 4.33s	remaining: 17.8s
196:	learn: 0.3957204	total: 4.35s	remaining: 17.7s
197:	learn: 0.3953448	total: 4.36s	remaining: 17.7s
198:	learn: 0.3950623	total: 4.37s	remaining: 17.6s
199:	learn: 0.3948994	total: 4.39s	remaining: 17.5s
200:	learn: 0.3945232	total: 4.4s	remaining: 17.5s
201:	learn: 0.3944318	total: 4.41s	remaining: 17.4s
202:	learn: 0.3939690	total: 4.43s	remaining: 17.4s
203:	learn: 0.3932898	total: 4.44s	remaining: 17.3s
204:	learn: 0.3930843	total: 4.45s	remaining: 17.3s
205:	learn: 0.3928382	total: 4.47s	remaining: 17.2s
206:	learn: 0.3923455	total: 4.48s	remaining: 17.2s
207:	learn: 0.3922285	total: 4.5s	remaining: 17.1s
208:	learn: 0.3921375	total: 4.52s	remaining: 17.1s
209:	learn: 0.3919444	total: 4.53s	remaining: 17s
210:	learn: 0.3917201	total: 4.54s	remaining: 17s
211:	learn: 0.3914550	total: 4.55s	remaining: 16.9s
212:	learn: 0.3913150	total: 4.57s	remaining: 16.9s
213:	learn: 0.3910516	total: 4.58s	remaining: 16.8s
214:	learn: 0.3909364	total: 4.6s	remaining: 16.8s
215:	learn: 0.3906476	total: 4.61s	remaining: 16.7s
216:	learn: 0.3902940	total: 4.63s	remaining: 16.7s
217:	learn: 0.3900124	total: 4.64s	remaining: 16.6s
218:	learn: 0.3893390	total: 4.65s	remaining: 16.6s
219:	learn: 0.3892105	total: 4.67s	remaining: 16.5s
220:	learn: 0.3891322	total: 4.67s	remaining: 16.5s
221:	learn: 0.3888803	total: 4.68s	remaining: 16.4s
222:	learn: 0.3887604	total: 4.7s	remaining: 16.4s
223:	learn: 0.3885465	total: 4.71s	remaining: 16.3s
224:	learn: 0.3880597	total: 4.73s	remaining: 16.3s
225:	learn: 0.3877707	total: 4.74s	remaining: 16.2s
226:	learn: 0.3873822	total: 4.76s	remaining: 16.2s
227:	learn: 0.3867995	total: 4.77s	remaining: 16.2s
228:	learn: 0.3863770	total: 4.79s	remaining: 16.1s
229:	learn: 0.3861173	total: 4.8s	remaining: 16.1s
230:	learn: 0.3860171	total: 4.82s	remaining: 16s
231:	learn: 0.3858469	total: 4.83s	remaining: 16s
232:	learn: 0.3855263	total: 4.84s	remaining: 15.9s
233:	learn: 0.3853425	total: 4.86s	remaining: 15.9s
234:	learn: 0.3847702	total: 4.87s	remaining: 15.9s
235:	learn: 0.3846535	total: 4.88s	remaining: 15.8s
236:	learn: 0.3844180	total: 4.89s	remaining: 15.8s
237:	learn: 0.3838852	total: 4.91s	remaining: 15.7s
238:	learn: 0.3837036	total: 4.92s	remaining: 15.7s
239:	learn: 0.3836402	total: 4.94s	remaining: 15.6s
240:	learn: 0.3833334	total: 4.95s	remaining: 15.6s
241:	learn: 0.3830317	total: 4.97s	remaining: 15.6s
242:	learn: 0.3828551	total: 4.98s	remaining: 15.5s
243:	learn: 0.3825650	total: 5s	remaining: 15.5s
244:	learn: 0.3821548	total: 5.01s	remaining: 15.4s
245:	learn: 0.3818148	total: 5.03s	remaining: 15.4s
246:	learn: 0.3817009	total: 5.04s	remaining: 15.4s
247:	learn: 0.3813915	total: 5.05s	remaining: 15.3s
248:	learn: 0.3811942	total: 5.07s	remaining: 15.3s
249:	learn: 0.3810161	total: 5.08s	remaining: 15.2s
250:	learn: 0.3808000	total: 5.09s	remaining: 15.2s
251:	learn: 0.3805521	total: 5.11s	remaining: 15.2s
252:	learn: 0.3801917	total: 5.12s	remaining: 15.1s
253:	learn: 0.3800945	total: 5.14s	remaining: 15.1s
254:	learn: 0.3799416	total: 5.15s	remaining: 15s
255:	learn: 0.3799005	total: 5.16s	remaining: 15s
256:	learn: 0.3795665	total: 5.17s	remaining: 14.9s
257:	learn: 0.3792238	total: 5.18s	remaining: 14.9s
258:	learn: 0.3789138	total: 5.2s	remaining: 14.9s
259:	learn: 0.3788019	total: 5.21s	remaining: 14.8s
260:	learn: 0.3786164	total: 5.22s	remaining: 14.8s
261:	learn: 0.3783711	total: 5.24s	remaining: 14.8s
262:	learn: 0.3780441	total: 5.25s	remaining: 14.7s
263:	learn: 0.3776415	total: 5.27s	remaining: 14.7s
264:	learn: 0.3774551	total: 5.28s	remaining: 14.6s
265:	learn: 0.3772462	total: 5.29s	remaining: 14.6s
266:	learn: 0.3770718	total: 5.31s	remaining: 14.6s
267:	learn: 0.3768024	total: 5.32s	remaining: 14.5s
268:	learn: 0.3765618	total: 5.34s	remaining: 14.5s
269:	learn: 0.3762424	total: 5.35s	remaining: 14.5s
270:	learn: 0.3759931	total: 5.37s	remaining: 14.4s
271:	learn: 0.3759134	total: 5.38s	remaining: 14.4s
272:	learn: 0.3757653	total: 5.4s	remaining: 14.4s
273:	learn: 0.3754410	total: 5.41s	remaining: 14.3s
274:	learn: 0.3751603	total: 5.42s	remaining: 14.3s
275:	learn: 0.3749928	total: 5.44s	remaining: 14.3s
276:	learn: 0.3746872	total: 5.45s	remaining: 14.2s
277:	learn: 0.3744668	total: 5.47s	remaining: 14.2s
278:	learn: 0.3742783	total: 5.48s	remaining: 14.2s
279:	learn: 0.3739105	total: 5.49s	remaining: 14.1s
280:	learn: 0.3737559	total: 5.51s	remaining: 14.1s
281:	learn: 0.3734688	total: 5.52s	remaining: 14.1s
282:	learn: 0.3729171	total: 5.54s	remaining: 14s
283:	learn: 0.3727878	total: 5.55s	remaining: 14s
284:	learn: 0.3724128	total: 5.56s	remaining: 14s
285:	learn: 0.3721431	total: 5.58s	remaining: 13.9s
286:	learn: 0.3720108	total: 5.58s	remaining: 13.9s
287:	learn: 0.3717586	total: 5.6s	remaining: 13.8s
288:	learn: 0.3716983	total: 5.61s	remaining: 13.8s
289:	learn: 0.3712268	total: 5.63s	remaining: 13.8s
290:	learn: 0.3711866	total: 5.64s	remaining: 13.7s
291:	learn: 0.3708699	total: 5.66s	remaining: 13.7s
292:	learn: 0.3706683	total: 5.67s	remaining: 13.7s
293:	learn: 0.3705595	total: 5.68s	remaining: 13.6s
294:	learn: 0.3704416	total: 5.7s	remaining: 13.6s
295:	learn: 0.3701639	total: 5.71s	remaining: 13.6s
296:	learn: 0.3699769	total: 5.73s	remaining: 13.6s
297:	learn: 0.3699368	total: 5.74s	remaining: 13.5s
298:	learn: 0.3697318	total: 5.75s	remaining: 13.5s
299:	learn: 0.3696472	total: 5.76s	remaining: 13.5s
300:	learn: 0.3695158	total: 5.78s	remaining: 13.4s
301:	learn: 0.3693187	total: 5.79s	remaining: 13.4s
302:	learn: 0.3689587	total: 5.81s	remaining: 13.4s
303:	learn: 0.3684912	total: 5.82s	remaining: 13.3s
304:	learn: 0.3682599	total: 5.84s	remaining: 13.3s
305:	learn: 0.3679953	total: 5.85s	remaining: 13.3s
306:	learn: 0.3678274	total: 5.86s	remaining: 13.2s
307:	learn: 0.3675514	total: 5.88s	remaining: 13.2s
308:	learn: 0.3673066	total: 5.89s	remaining: 13.2s
309:	learn: 0.3670632	total: 5.91s	remaining: 13.1s
310:	learn: 0.3667853	total: 5.92s	remaining: 13.1s
311:	learn: 0.3666872	total: 5.93s	remaining: 13.1s
312:	learn: 0.3663692	total: 5.95s	remaining: 13.1s
313:	learn: 0.3660975	total: 5.96s	remaining: 13s
314:	learn: 0.3658229	total: 5.97s	remaining: 13s
315:	learn: 0.3657110	total: 5.99s	remaining: 13s
316:	learn: 0.3656710	total: 6s	remaining: 12.9s
317:	learn: 0.3654073	total: 6.01s	remaining: 12.9s
318:	learn: 0.3653191	total: 6.03s	remaining: 12.9s
319:	learn: 0.3651340	total: 6.04s	remaining: 12.8s
320:	learn: 0.3648745	total: 6.05s	remaining: 12.8s
321:	learn: 0.3646073	total: 6.07s	remaining: 12.8s
322:	learn: 0.3643927	total: 6.08s	remaining: 12.7s
323:	learn: 0.3641267	total: 6.09s	remaining: 12.7s
324:	learn: 0.3638610	total: 6.11s	remaining: 12.7s
325:	learn: 0.3635926	total: 6.12s	remaining: 12.7s
326:	learn: 0.3634041	total: 6.13s	remaining: 12.6s
327:	learn: 0.3633666	total: 6.14s	remaining: 12.6s
328:	learn: 0.3630706	total: 6.16s	remaining: 12.6s
329:	learn: 0.3629635	total: 6.17s	remaining: 12.5s
330:	learn: 0.3624608	total: 6.18s	remaining: 12.5s
331:	learn: 0.3622346	total: 6.2s	remaining: 12.5s
332:	learn: 0.3618276	total: 6.21s	remaining: 12.4s
333:	learn: 0.3616338	total: 6.23s	remaining: 12.4s
334:	learn: 0.3614089	total: 6.24s	remaining: 12.4s
335:	learn: 0.3612306	total: 6.25s	remaining: 12.4s
336:	learn: 0.3610314	total: 6.26s	remaining: 12.3s
337:	learn: 0.3607598	total: 6.28s	remaining: 12.3s
338:	learn: 0.3604258	total: 6.29s	remaining: 12.3s
339:	learn: 0.3601632	total: 6.31s	remaining: 12.2s
340:	learn: 0.3600275	total: 6.32s	remaining: 12.2s
341:	learn: 0.3598803	total: 6.33s	remaining: 12.2s
342:	learn: 0.3593974	total: 6.35s	remaining: 12.2s
343:	learn: 0.3591915	total: 6.35s	remaining: 12.1s
344:	learn: 0.3589199	total: 6.37s	remaining: 12.1s
345:	learn: 0.3584358	total: 6.38s	remaining: 12.1s
346:	learn: 0.3583788	total: 6.39s	remaining: 12s
347:	learn: 0.3580264	total: 6.4s	remaining: 12s
348:	learn: 0.3577634	total: 6.42s	remaining: 12s
349:	learn: 0.3574441	total: 6.43s	remaining: 11.9s
350:	learn: 0.3572694	total: 6.44s	remaining: 11.9s
351:	learn: 0.3569173	total: 6.46s	remaining: 11.9s
352:	learn: 0.3567480	total: 6.47s	remaining: 11.9s
353:	learn: 0.3563919	total: 6.49s	remaining: 11.8s
354:	learn: 0.3559926	total: 6.5s	remaining: 11.8s
355:	learn: 0.3558157	total: 6.52s	remaining: 11.8s
356:	learn: 0.3554002	total: 6.53s	remaining: 11.8s
357:	learn: 0.3551700	total: 6.54s	remaining: 11.7s
358:	learn: 0.3549136	total: 6.56s	remaining: 11.7s
359:	learn: 0.3545985	total: 6.57s	remaining: 11.7s
360:	learn: 0.3545041	total: 6.58s	remaining: 11.7s
361:	learn: 0.3542167	total: 6.6s	remaining: 11.6s
362:	learn: 0.3538758	total: 6.61s	remaining: 11.6s
363:	learn: 0.3537082	total: 6.63s	remaining: 11.6s
364:	learn: 0.3534951	total: 6.64s	remaining: 11.5s
365:	learn: 0.3531554	total: 6.65s	remaining: 11.5s
366:	learn: 0.3526515	total: 6.67s	remaining: 11.5s
367:	learn: 0.3522413	total: 6.68s	remaining: 11.5s
368:	learn: 0.3518605	total: 6.69s	remaining: 11.4s
369:	learn: 0.3515481	total: 6.71s	remaining: 11.4s
370:	learn: 0.3512954	total: 6.72s	remaining: 11.4s
371:	learn: 0.3510636	total: 6.74s	remaining: 11.4s
372:	learn: 0.3507696	total: 6.75s	remaining: 11.3s
373:	learn: 0.3505661	total: 6.76s	remaining: 11.3s
374:	learn: 0.3503295	total: 6.78s	remaining: 11.3s
375:	learn: 0.3501957	total: 6.79s	remaining: 11.3s
376:	learn: 0.3500128	total: 6.8s	remaining: 11.2s
377:	learn: 0.3497443	total: 6.82s	remaining: 11.2s
378:	learn: 0.3495571	total: 6.83s	remaining: 11.2s
379:	learn: 0.3490780	total: 6.84s	remaining: 11.2s
380:	learn: 0.3487017	total: 6.86s	remaining: 11.1s
381:	learn: 0.3484262	total: 6.87s	remaining: 11.1s
382:	learn: 0.3482110	total: 6.88s	remaining: 11.1s
383:	learn: 0.3480140	total: 6.9s	remaining: 11.1s
384:	learn: 0.3479022	total: 6.91s	remaining: 11s
385:	learn: 0.3476206	total: 6.92s	remaining: 11s
386:	learn: 0.3474330	total: 6.94s	remaining: 11s
387:	learn: 0.3470902	total: 6.95s	remaining: 11s

In [98]:
X_test = df.drop(columns=["target"])
y_test = df["target"]
prediction = model.predict(X_test)
probas = model.predict_proba(X_test)

In [99]:
from sklearn.metrics import confusion_matrix, roc_auc_score, precision_score, recall_score, f1_score, log_loss
# импортируйте необходимые вам модули

# заведите словарь со всеми метриками
metrics = {}

# посчитайте метрики из модуля sklearn.metrics
# err_1 — ошибка первого рода
# err_2 — ошибка второго рода
_, err1, _, err2 = confusion_matrix(y_test, prediction, normalize="all").ravel()
auc = roc_auc_score(y_test, probas[:, 1])
precision = precision_score(y_test, prediction)
recall = recall_score(y_test, prediction)
f1 = f1_score(y_test, prediction)
logloss = log_loss(y_test, prediction)

# запишите значения метрик в словарь
metrics["err1"] = err1
metrics["err2"] = err2
metrics["auc"] = auc
metrics["precision"] = precision
metrics["recall"] = recall
metrics["f1"] = f1
metrics["logloss"] = logloss

In [100]:
pip_requirements = "./requirements.txt"
signature = mlflow.models.infer_signature(X_test, prediction)
input_example = X_test[:10]
metadata = {"model_type": "monthly"}

/home/mle-user/mle_projects/mle-mlflow/.venv/lib/python3.10/site-packages/mlflow/models/signature.py:212: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details.
  inputs = _infer_schema(model_input) if model_input is not None else None

In [101]:
RUN_NAME = "preprocessing"

experiment_id = mlflow.get_experiment_by_name(EXPERIMENT_NAME).experiment_id

with mlflow.start_run(run_name=RUN_NAME, experiment_id=experiment_id) as run:
    run_id = run.info.run_id
    # ваш код здесь
    model_info = mlflow.catboost.log_model(
        cb_model=model,
        artifact_path="models",
        pip_requirements=pip_requirements,
        signature=signature,
        input_example=input_example,
        metadata=metadata,
        registered_model_name=REGISTRY_MODEL_NAME,
        await_registration_for=60,
    )
    mlflow.log_metrics(metrics)

Registered model 'churn_model_simonreise_catboost_basic' already exists. Creating a new version of this model...
2026/03/07 08:43:33 INFO mlflow.tracking._model_registry.client: Waiting up to 60 seconds for model version to finish creation. Model name: churn_model_simonreise_catboost_basic, version 4
Created version '4' of model 'churn_model_simonreise_catboost_basic'.